# Generated by Django 5.1.3 on 2025-01-03 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_order_date_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 18, 21, 8, 804227)),
        ),
    ]
