# Generated by Django 5.1.3 on 2025-01-16 21:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_product_star_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 0, 50, 51, 809557)),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
