# Generated by Django 5.1.3 on 2025-01-31 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_order_date_alter_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 17, 59, 40, 747433)),
        ),
    ]
